// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW9WxJygI4kAkfrEPnxOw8O3DWDBAp_ks',
    appId: '1:403363679381:web:e8bee8a0a75cc2188f9f9c',
    messagingSenderId: '403363679381',
    projectId: 'taayza-35d71',
    authDomain: 'taayza-35d71.firebaseapp.com',
    storageBucket: 'taayza-35d71.appspot.com',
    measurementId: 'G-DX5K5GJQET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX7qhj9kPh_J_8mqE6m1OmhIEnkOE5ulI',
    appId: '1:403363679381:android:7313f5f91113f8138f9f9c',
    messagingSenderId: '403363679381',
    projectId: 'taayza-35d71',
    storageBucket: 'taayza-35d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmorWR7kqS0dev8IVo6RQEsdBGYg_RNCM',
    appId: '1:403363679381:ios:de4eb27a1534005c8f9f9c',
    messagingSenderId: '403363679381',
    projectId: 'taayza-35d71',
    storageBucket: 'taayza-35d71.appspot.com',
    iosClientId: '403363679381-4i6k7o51h884etesrpfcevdguqg1pd87.apps.googleusercontent.com',
    iosBundleId: 'com.taayza.taayza',
  );
}
